//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pet_Shop.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MasterPol_Entities : DbContext
    {

        private static MasterPol_Entities _context = new MasterPol_Entities();
        public static MasterPol_Entities GetContext()
        {
            if (_context == null)
            {
                _context = new MasterPol_Entities();
            }
            return _context;
        }


        public MasterPol_Entities()
            : base("name=MasterPol_Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AdressCity> AdressCity { get; set; }
        public virtual DbSet<AdressIndex> AdressIndex { get; set; }
        public virtual DbSet<AdressRegion> AdressRegion { get; set; }
        public virtual DbSet<AdressStreet> AdressStreet { get; set; }
        public virtual DbSet<CompanyName> CompanyName { get; set; }
        public virtual DbSet<CompanyType> CompanyType { get; set; }
        public virtual DbSet<MaterialType> MaterialType { get; set; }
        public virtual DbSet<Orders> Orders { get; set; }
        public virtual DbSet<Partner> Partner { get; set; }
        public virtual DbSet<Product> Product { get; set; }
        public virtual DbSet<ProductName> ProductName { get; set; }
        public virtual DbSet<ProductType> ProductType { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
    }
}
