//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pet_Shop.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Partner
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Partner()
        {
            this.Orders = new HashSet<Orders>();
        }
    
        public int id { get; set; }
        public int companyType { get; set; }
        public int companyName { get; set; }
        public string lastname { get; set; }
        public string name { get; set; }
        public string surname { get; set; }
        public string email { get; set; }
        public string phone { get; set; }
        public int index { get; set; }
        public int region { get; set; }
        public int city { get; set; }
        public int street { get; set; }
        public int building { get; set; }
        public string inn { get; set; }
        public int rating { get; set; }
    
        public virtual AdressCity AdressCity { get; set; }
        public virtual AdressIndex AdressIndex { get; set; }
        public virtual AdressRegion AdressRegion { get; set; }
        public virtual AdressStreet AdressStreet { get; set; }
        public virtual CompanyName CompanyName1 { get; set; }
        public virtual CompanyType CompanyType1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Orders> Orders { get; set; }
    }
}
